language: php

php:
  - '5.6'
  - '7.0'

install:
  - sudo apt-get update
  - sudo apt-get install -y --force-yes curl lsb-release

before_script:
  - sudo bash ./cloudynitzar.sh

script:
  - tests/01_php_web_interface.sh
  - tests/02_serf_daemon.sh
