language: php

php:
  - '5.6'
  - '7.0'

install:
  - sudo apt-get update
  - sudo apt-get install -y --force-yes curl lsb-release

before_script:
  - sudo su -c "bash $PWD/cloudynitzar.sh"

script:
  - tests/01_php_web_interface.sh
  - tests/02_serf_daemon.sh
  - tests/03_web_interface_login.sh
