---
- hosts: all
  become: yes
  tasks:
  - name: Create Cloudy log directory
    file:
      path: /var/log/cloudy
      state: directory

  - name: Add Debian backport repository
    apt_repository:
      repo: "deb http://ftp.debian.org/debian {{ ansible_distribution_release }}-backports main contrib"
      state: present
      update_cache: no
    when: ansible_distribution == "Debian"

  - name: Add Clommunity repository
    apt_repository:
      repo: deb http://repo.clommunity-project.eu/debian unstable/
      state: present
      filename: cloudy
      update_cache: no

  - name: Add key for Clommunity
    shell: gpg --keyserver keys.gnupg.net --recv-key A59C5DC8 && gpg --export --armor A59C5DC8 | sudo apt-key add -

  - name: Add Guifi repository
    apt_repository:
      repo: deb http://serveis.guifi.net/debian guifi/
      state: present
      filename: guifi
      update_cache: no

  - name: Add key for Guifi
    shell: gpg --keyserver keys.gnupg.net --recv-key 2E484DAB && gpg --export --armor 2E484DAB | sudo apt-key add -

  #We update the cache seperately because the Guifi repo fails due to a GPG error. 
  #The failure occurs when using the original cloudynitzar script.
  - name: Update apt packages
    apt:
      update_cache: yes
    ignore_errors: yes

  - name: Install release independent packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: no
    vars:
      packages:
      - unzip
      - curl
      - dirmngr
      - iproute2
      - openssh-server
      - openssh-client
      - make
      - jq
      - tahoe-lafs
      - python2.7
      - g++
      - checkinstall
      - locales
      - php
      - php-ssh2
      - libapache2-mod-encoding
      - git

  - name: Install Bionic 18 dependant packages
    apt:
      name: "{{ bionic_packages }}"
      state: present
      update_cache: no
    vars:
      bionic_packages:
      - php-sqlite3
      - php-curl
    when: ansible_distribution_release == "bionic"

  - name: Install Debian 10 dependant packages.
    apt:
      name: "{{ bionic_packages }}"
      state: present
      update_cache: no
    vars:
      bionic_packages:
      - php-sqlite3
      - php-curl
    when: ansible_distribution_release == "buster"

  - name: Install Focal 20 dependant packages
    apt:
      name: "{{ focal_packages }}"
      state: present
      update_cache: no
    vars:
      focal_packages:
      - php5-sqlite
      - php5-curl
    when: ansible_distribution_release == "focal"

  - name: Download cDistro script
    get_url:
      url: https://raw.githubusercontent.com/Clommunity/lbmake/master/hooks/cDistro.chroot
      dest: /etc/cDistro.chroot
      mode: '0777'

  - name: Download avahi-ps script
    get_url:
      url: https://raw.githubusercontent.com/Clommunity/lbmake/master/hooks/avahi-ps.chroot
      dest: /etc/avahi-ps.chroot
      mode: '0777'

  - name: Download serf script
    get_url:
      url: https://raw.githubusercontent.com/Clommunity/lbmake/master/hooks/serf.chroot
      dest: /etc/serf.chroot
      mode: '0777'

  - name: Download ipfs script
    get_url:
      url: https://raw.githubusercontent.com/Clommunity/lbmake/master/hooks/ipfs.chroot
      dest: /etc/ipfs.chroot
      mode: '0777'
    
  - name: Run cDistro script
    shell: /etc/cDistro.chroot

  - name: Run avahi script
    shell: /etc/avahi-ps.chroot

  - name: Run serf script
    shell: /etc/serf.chroot

  - name: Run ipfs script
    shell: /etc/ipfs.chroot

  - name: Set primary network interface
    lineinfile:
      path: /etc/cloudy/cloudy.conf
      line: PRIMARYINTERFACE="{{ ansible_default_ipv4.interface }}"

  - name: Restart cloudy daemon
    service: 
      name: cdistro
      state: restarted
      
  - name: Start serf daemon
    service: 
      name: serf
      state: started