---
- hosts: all
  become: yes
  tasks:
  - name: Install packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - unzip
      - curl
      - dirmngr
      - iproute2
      - openssh-server
      - openssh-client
      - make
      - jq
      - tahoe-lafs
      - python2.7
      - g++
      - checkinstall
      - locales
      - php
      - php-ssh2
      - php-sqlite3
      - php-curl
      - libapache2-mod-encoding
      - git

  - name: Run cDistro script
    script: cDistro.chroot

  - name: Run avahi script
    script: avahi-ps.chroot

  - name: Run serf script
    script: serf.chroot

  - name: Run ipfs script
    script: ipfs.chroot

  - name: Get the primary network interface
    shell: route | grep '^default' | grep -o '[^ ]*$'
    register: primaryiface

  - name: Set primary network interface
    lineinfile:
      path: /etc/cloudy/cloudy.conf
      line: PRIMARYINTERFACE="{{ primaryiface.stdout }}"

  - name: Restart cloudy daemon
    service: 
      name: cdistro
      state: restarted
      
  - name: Start serf daemon
    service: 
      name: serf
      state: started