---
- hosts: all
  become: yes
  tasks:
  - name: Install release independent packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - unzip
      - curl
      - dirmngr
      - iproute2
      - openssh-server
      - openssh-client
      - make
      - jq
      - tahoe-lafs
      - python2.7
      - g++
      - checkinstall
      - locales
      - php
      - php-ssh2
      - libapache2-mod-encoding
      - git

  - name: Install Bionic 18 dependant packages
    apt:
      name: "{{ bionic_packages }}"
      state: present
      update_cache: no
    vars:
      bionic_packages:
      - php-sqlite3
      - php-curl
    when: ansible_distribution_release == "bionic"

  - name: Install Focal 20 dependant packages
    apt:
      name: "{{ focal_packages }}"
      state: present
      update_cache: no
    vars:
      focal_packages:
      - php5-sqlite
      - php5-curl
    when: ansible_distribution_release == "focal"

  - name: Run cDistro script
    script: cDistro.chroot

  - name: Run avahi script
    script: avahi-ps.chroot

  - name: Run serf script
    script: serf.chroot

  - name: Run ipfs script
    script: ipfs.chroot

  - name: Set primary network interface
    lineinfile:
      path: /etc/cloudy/cloudy.conf
      line: PRIMARYINTERFACE="{{ ansible_default_ipv4.interface }}"

  - name: Restart cloudy daemon
    service: 
      name: cdistro
      state: restarted
      
  - name: Start serf daemon
    service: 
      name: serf
      state: started