---
- hosts: all
  become: yes
  roles:
    - cloudy
  
- hosts: kubernetes
  vars:
    k3s_become_for_all: true
    k3s_etcd_datastore: true
    k3s_use_experimental: true  # Note this is required for k3s < v1.19.5+k3s1
  roles:
    - role: xanmanning.k3s